name: Builds
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["apk --debug"]
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v2.4.0

      - run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v2
      - run: flutter pub get -v

      - run: flutter build ${{ matrix.target }}